stats_to_collects = {
    'boons': [
        'might',
        'fury',
        'quickness',
        'alacrity',
        'protection',
        'regeneration',
        'vigor',
        'aegis',
        'stability',
        'swiftness',
        'resistance',
        'resolution'
	],
    'support buffs': [
        'superspeed',
		'fire',
		'frost',
		'light',
		'shocking',
		'chaos',
		'dark'
	],
    'offensive buffs': [
		'unblockable',
        'ashes of the just',
        'one wolf pack',
        'spider venom',
        'rot wallow venom',
        'static charge'
	],
    'defensive buffs': [
        'rite of the great dwarf',
        'infuse light',
        'eternal oasis',
        'unbroken lines',
        'dolyak stance',
        'bear stance',
        'vampiric aura',
        'last rites',
        'soothing mist',
        'rebound'
	],
	'conditions': [
		'bleeding',
		'burning',
		'confusion',
		'poisoned',
		'torment',
		'blind',
		'chilled',
		'crippled',
        'fear',
        'imobile',
        'slow',
        'weakness',
        'vulnerability'
	],
	'defenses': [
		'damageTaken',
		'conditionDamageTaken',
		'powerDamageTaken',
		'strikeDamageTaken',
		'lifeLeechDamageTaken',
		'downedDamageTaken',
		'breakbarDamageTaken',
		'blockedCount',
		'evadedCount',
		'missedCount',
		'dodgeCount',
		'invulnedCount',
		'damageBarrier',
		'interruptedCount',
		'downCount',
		'downDuration',
		'deadCount',
		'deadDuration',
		'dcCount',
		'dcDuration',
		'boonStrips',
		'boonStripsTime',
		'conditionCleanses',
		'conditionCleansesTime',
        'receivedCrowdControl',
        'receivedCrowdControlDuration'
	],
	'support': [
		'resurrects',
		'resurrectTime',
		'condiCleanse',
		'condiCleanseTime',
		'condiCleanseSelf',
		'condiCleanseTimeSelf',
		'boonStrips',
		'boonStripsTime',
        'stunBreak',
        'removedStunDuration'
	],
	'healing': [
		'outgoingHealingAllies',
        'alliedHealingDist',
        'outgoingBarrierAllies',
        'alliedBarrierDist'
	],
	'statsAll': [
		'wasted',
		'timeWasted',
		'saved',
		'timeSaved',
		'stackDist',
		'distToCom',
		'avgBoons',
		'avgActiveBoons',
		'avgConditions',
		'avgActiveConditions',
		'swapCount',
		'skillCastUptime',
		'skillCastUptimeNoAA',
		'totalDamageCount',
		'totalDmg',
		'directDamageCount',
		'directDmg',
		'connectedDirectDamageCount',
		'connectedDirectDmg',
		'connectedDamageCount',
		'connectedDmg',
		'critableDirectDamageCount',
		'criticalRate',
		'criticalDmg',
		'flankingRate',
		'againstMovingRate',
		'glanceRate',
		'missed',
		'evaded',
		'blocked',
		'interrupts',
		'invulned',
		'killed',
		'downed',
		'downContribution',
		'connectedPowerCount',
		'connectedPowerAbove90HPCount',
		'connectedConditionCount',
		'connectedConditionAbove90HPCount',
		'againstDownedCount',
		'againstDownedDamage',
	],
	'targetDamageDist': [
		'totalDamage',
		'totalBreakbarDamage',
		'min',
		'max',
		'hits',
		'connectedHits',
		'crit',
		'glance',
		'flank',
		'againstMoving',
		'missed',
		'invulned',
		'interrupted',
		'evaded',
		'blocked',
		'shieldDamage',
		'critDamage',
		'id',
		'indirectDamage',
	],
	'dpsTargets': [
		'dps',
		'damage',
		'condiDps',
		'condiDamage',
		'powerDps',
		'powerDamage',
		'breakbarDamage',
		'actorDps',
		'actorDamage',
		'actorCondiDps',
		'actorCondiDamage',
		'actorPowerDps',
		'actorPowerDamage',
		'actorBreakbarDamage',
	],
	'totalDamageTaken': [
		'totalDamage',
		'totalBreakbarDamage',
		'min',
		'max',
		'hits',
		'connectedHits',
		'crit',
		'glance',
		'flank',
		'againstMoving',
		'missed',
		'invulned',
		'interrupted',
		'evaded',
		'blocked',
		'shieldDamage',
		'critDamage',
		'id',
		'indirectDamage',
	],
	'rotation': {}
	}
