stats_to_collects = {
	'defenses' = [
		'damageTaken',
		'conditionDamageTaken',
		'powerDamageTaken',
		'strikeDamageTaken',
		'lifeLeechDamageTaken,
		'downedDamageTaken',
		'breakbarDamageTaken',
		'blockedCount',
		'evadedCount',
		'missedCount',
		'dodgeCount',
		'invulnedCount',
		'damageBarrier',
		'interruptedCount',	0
		'downCount',
		'downDuration',
		'deadCount',
		'deadDuration',
		'dcCount',
		'dcDuration',
		'boonStrips',
		'boonStripsTime',
		'conditionCleanses',
		'conditionCleansesTime'
	]

	'support' = [
		'resurrects',
		'resurrectTime',
		'condiCleanse',
		'condiCleanseTime',
		'condiCleanseSelf',
		'condiCleanseTimeSelf',
		'boonStrips',
		'boonStripsTime',
	]

	'statsAll' = [
		'wasted',
		'timeWasted',
		'saved',
		'timeSaved',
		'stackDist',
		'distToCom',
		'avgBoons',
		'avgActiveBoons',
		'avgConditions',
		'avgActiveConditions',
		'swapCount',
		'skillCastUptime',
		'skillCastUptimeNoAA',
		'totalDamageCount',
		'totalDmg',
		'directDamageCount',
		'directDmg',
		'connectedDirectDamageCount',
		'connectedDirectDmg',
		'connectedDamageCount',
		'connectedDmg',
		'critableDirectDamageCount',
		'criticalRate',
		'criticalDmg',
		'flankingRate',
		'againstMovingRate',
		'glanceRate',
		'missed',
		'evaded',
		'blocked',
		'interrupts',
		'invulned',
		'killed',
		'downed',
		'downContribution',
		'connectedPowerCount',
		'connectedPowerAbove90HPCount',
		'connectedConditionCount',
		'connectedConditionAbove90HPCount',
		'againstDownedCount',
		'againstDownedDamage',
	]

	'targetDamageDist' = [
		'totalDamage',
		'totalBreakbarDamage',
		'min',
		'max',
		'hits',
		'connectedHits',
		'crit',
		'glance',
		'flank',
		'againstMoving',
		'missed',
		'invulned',
		'interrupted',
		'evaded',
		'blocked',
		'shieldDamage',
		'critDamage',
		'id',
		'indirectDamage',
	]

	'dpsTargets' = [
		'dps',
		'damage',
		'condiDps',
		'condiDamage',
		'powerDps',
		'powerDamage',
		'breakbarDamage',
		'actorDps',
		'actorDamage',
		'actorCondiDps',
		'actorCondiDamage',
		'actorPowerDps',
		'actorPowerDamage',
		'actorBreakbarDamage',
	]

	'totalDamageTaken' = [
		'totalDamage',
		'totalBreakbarDamage',
		'min',
		'max',
		'hits',
		'connectedHits',
		'crit',
		'glance',
		'flank',
		'againstMoving',
		'missed',
		'invulned',
		'interrupted',
		'evaded',
		'blocked',
		'shieldDamage',
		'critDamage',
		'id',
		'indirectDamage',
	]

	'rotation' = [
		'id',
		'skills: [
			'castTime',
			'duration',
			'timeGained',
			'quickness'
		]
	]
}